# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  # Import auto-detected (non-detected) hardware modules
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  #########################
  # Kernel & initrd modules
  #########################

  # Basic kernel modules for NVMe, USB, LVM, MDADM
  boot.initrd.availableKernelModules = [
    "nvme" "xhci_pci" "ahci" "mpt3sas" "usbhid" "sd_mod"
  ];
  # Snapshot support for LVM caching
  boot.initrd.kernelModules = [ "dm-snapshot" "dm-cache-default" ];

  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  #########################
  # File Systems
  #########################

  fileSystems."/" = {
    # Mount the root LV (must exist before install or be created manually)
    device = "/dev/mapper/homeserver--vg-root";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/27EE-4CFA";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  fileSystems."/data" = {
    # Mount the cached data LV on your RAID array
    device = "/dev/mapper/vg_redundant-lv_data";
    fsType = "xfs";
  };

  swapDevices = [
    { device = "/dev/mapper/homeserver--vg-swap"; }
  ];

  #########################
  # Platform & CPU
  #########################

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
